blank_issues_enabled: true
contact_links:
  - name: ğŸ¤” å•é¡Œ
    url: https://github.com/ItzMiracleOwO/discord-linuxserver/issues
    about: ä½ å¯ä»¥é–‹å•ŸIssues, æˆ‘å€‘å¾ˆå¿«å°±æœƒç‚ºæ‚¨æä¾›æ”¯æ´!
  - name: ğŸ’¬ èŠå¤©
    url: https://github.com/ItzMiracleOwO/discord-linuxserver/discussions
    about: æƒ³è¦èˆ‡å…¶ä»–äººè¨è«–é—œæ–¼æ©Ÿå™¨äººçš„è©±é¡Œå—? åŠ å…¥æˆ‘å€‘çš„Discussionså§!
